[package]
name = "config-parse"
version = "1.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
confy = "0.4.0"
serde = {version="1.0.136", features = ["derive"]}
config = "0.12.0"
csv = "1.1"
nom = "7.1.1"
